"""empty message

Revision ID: 112f3fdd4541
Revises: f4ea9c5797c4
Create Date: 2024-06-13 16:44:53.149504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112f3fdd4541'
down_revision = 'f4ea9c5797c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
