"""empty message

Revision ID: 946e60a31fbf
Revises: 
Create Date: 2024-06-11 16:47:04.274702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946e60a31fbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('formacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formacao_id'], ['formacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_formacao',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('formacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formacao_id'], ['formacao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'formacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor_formacao')
    op.drop_table('curso')
    op.drop_table('professor')
    op.drop_table('formacao')
    # ### end Alembic commands ###
